config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :snips
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "snips#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snip.rb
class Snip < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :snips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def acount_update_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/snips_controller.rb
class SnipsController < ApplicationController
  before_action :set_snip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /snips
  # GET /snips.json
  def index
    @snips = Snip.all.order("created_at DESC")
    @snip = Snip.new
  end

  # GET /snips/1
  # GET /snips/1.json
  def show
  end

  # GET /snips/new
  def new
    @snip = current_user.snips.build
  end

  # GET /snips/1/edit
  def edit
  end

  # POST /snips
  # POST /snips.json
  def create
    @snip = current_user.snips.build(snip_params)

    respond_to do |format|
      if @snip.save
        format.html { redirect_to root_path, notice: 'Snip was successfully created.' }
        format.json { render :show, status: :created, location: @snip }
      else
        format.html { render :new }
        format.json { render json: @snip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snips/1
  # PATCH/PUT /snips/1.json
  def update
    respond_to do |format|
      if @snip.update(snip_params)
        format.html { redirect_to @snip, notice: 'Snip was successfully updated.' }
        format.json { render :show, status: :ok, location: @snip }
      else
        format.html { render :edit }
        format.json { render json: @snip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snips/1
  # DELETE /snips/1.json
  def destroy
    @snip.destroy
    respond_to do |format|
      format.html { redirect_to snips_url, notice: 'Snip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snip
      @snip = Snip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snip_params
      params.require(:snip).permit(:snip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snips_helper.rb
module SnipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snippers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Snippers</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to 'New Snip', root_path, class: "button is-info is-inverted" %>
                </p>
                <% if user_signed_in? %>
                  <p class="control">
                    <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                  </p>
                  <p>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %> 
                  </p>
                <% else %>
                  <p class="control">
                    <%= link_to'Sign In', new_user_session_path, class: "button is-info" %>
                  </p>
                  <p class="control">
                    <%= link_to'Sign Up', new_user_registration_path, class: "button is-info" %>
                  </p>
                <% end %>
                  </div>
            </div>
          </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/snips/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
            </p>
        </figure>
        <div class="media-content">
            <%= render 'snips/form' %>
        </div>
    </article>
    <% end %>


    <% @snips.each do | snip | %>
        <div class="box">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                    <%= gravatar_image_tag(snip.user.email, size: 64, alt: snip.user.name) %>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <strong><%= snip.user.name %></strong><br />
                        <small><%= snip.user.username %></small><br/>
                        <p><%= snip.snip %></p>
                    </div>
                    <% if user_signed_in? && current_user.id == snip.user_id %>
                    <nav class="level">
                        <div class="level-left is-mobile">
                            <%= link_to snip, class: "level-item" do%>
                                <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                            <% end %>
                            <%= link_to edit_snip_path(snip), class: "level-item" do%>
                                <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                            <% end %>
                            <%= link_to snip, method: :delete, data: {confirm: "Bye bye snip?" } do%>
                                <span class="icon"><i class="fa fa-trash" aria-hidden="true"></i></span>
                            <% end %>
                        </div>
                    <% end %>  
                    </nav>
                </div>
            </article>
        </div>
    <% end %>
</div>

app/views/snips/_form.html.erb
<%= simple_form_for(@snip) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :snip, label: "Snippy Snip", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new snip...", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/snips/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
                        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Snips</p>
						<p class="title is-6"><%= current_user.snips.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">214</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">69M</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/snips/_trends.html.erb
<div class="column is one-quarter">
    <nav class ="panel">
        <p class="panel-heading">Trending Topics</p>
        <a class= "panel-block">
            Sea Games
        </a>
        <a class= "panel-block">
            Digong, buntis!
        </a>
        <a class= "panel-block">
            CSI Best Org
        </a>
        <a class= "panel-block">
            Ivan Pogi
        </a>
        <a class= "panel-block">
            Kaldero ni mama, 50 pesos
        </a>
        <a class= "panel-block">
            Nigs Canteen naubusan ng kutsara
        </a>
        <a class= "panel-block">
            Letter Y tinanggal sa Alphabet
        </a>
        <a class= "panel-block">
            3peat
        </a>
        
    </nav>
</div>

app/views/snips/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to Follow</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/32x32.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Ivan Loristo</strong>
                            <small>@jfloristo</small>
                        </P>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/32x32.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Ridge Cunanan</strong>
                            <small>@rcunanan</small>
                        </P>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/32x32.png">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong>Lhee Crisostomo</strong>
                            <small>@lcrisostomo</small>
                        </P>
                    </div>
                </div>
            </article>
        </div>
    </nav>
</div>

app/views/snips/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Snip</h1>
				<%= render 'form', snip: @snip %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', snips_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/snips/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
      <%= render 'profile' %>
      <% else %>
      <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/snips/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Snip</h1>
					<%= render 'form', tweeet: @snip %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', snips_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/snips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Snip:</strong>
  <%= @snip.snip %>
</p>

<%= link_to 'Edit', edit_snip_path(@snip) %> |
<%= link_to 'Back', snips_path %>